In [16]:
import cv2
import numpy as np

# Load HAAR face classifier
face_classifier = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

# Load functions
def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_classifier.detectMultiScale(gray, 1.3, 5)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

# Initialize Webcam
cap = cv2.VideoCapture(0)
count = 0

# Collect 100 samples of your face from webcam input
while True:

    ret, frame = cap.read()
    if face_extractor(frame) is not None:
        count += 1
        face = cv2.resize(face_extractor(frame), (200, 200))
        face = cv2.cvtColor(face, cv2.COLOR_BGR2GRAY)

        # Save file in specified directory with unique name
        file_name_path = './naman/face' + str(count) + '.jpg'
        cv2.imwrite(file_name_path, face)

        # Put count on images and display live count
        cv2.putText(face, str(count), (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
        cv2.imshow('Face Cropper', face)
        
    else:
        print("Face not found")
        pass

    if cv2.waitKey(1) == 13 or count == 100: #13 is the Enter Key
        break
        
cap.release()
cv2.destroyAllWindows()      
print("Collecting Samples Complete")

Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found


In [17]:
import cv2
import numpy as np
from os import listdir
from os.path import isfile, join
print(cv2.__version__)
# Get the training data we previously made
data_path = './naman/'
# a=listdir('d:/faces')
# print(a)
# """
onlyfiles = [f for f in listdir(data_path) if isfile(join(data_path, f))]
#print(onlyfiles)
# Create arrays for training data and labels
Training_Data, Labels = [], []

# Open training images in our datapath
# Create a numpy array for training data
for i, files in enumerate(onlyfiles):
    image_path = data_path+ onlyfiles[i]
    images = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    Training_Data.append(np.asarray(images, dtype=np.uint8))
    Labels.append(i)
# 
# Create a numpy array for both training data and labels
Labels = np.asarray(Labels, dtype=np.int32)
vimal_model=cv2.face_LBPHFaceRecognizer.create()
# Initialize facial recognizer
# model = cv2.face_LBPHFaceRecognizer.create()
# model=cv2.f
# NOTE: For OpenCV 3.0 use cv2.face.createLBPHFaceRecognizer()

# Let's train our model 
vimal_model.train(np.asarray(Training_Data), np.asarray(Labels))
print("Model trained sucessefully")



3.3.1
./naman/face1.jpg
[[ 0  0  0 ...  1  1  0]
 [ 0  0  0 ...  3  2  2]
 [ 0  0  0 ...  3  2  2]
 ...
 [ 2  5 10 ...  1  1  1]
 [ 1  3  8 ...  1  1  1]
 [ 1  1  7 ...  1  1  1]]
./naman/face2.jpg
[[ 0  0  0 ...  2  1  1]
 [ 0  0  0 ...  2  2  1]
 [ 0  0  0 ...  2  2  1]
 ...
 [14 16 18 ...  2  2  2]
 [15 17 19 ...  2  2  2]
 [15 18 19 ...  2  2  2]]
./naman/face3.jpg
[[ 0  0  0 ...  2  1  1]
 [ 0  0  0 ...  2  1  1]
 [ 0  0  0 ...  1  1  1]
 ...
 [16 16 18 ...  1  1  1]
 [17 15 17 ...  1  1  2]
 [17 14 16 ...  1  1  2]]
./naman/face4.jpg
[[ 4  4  5 ... 13 12 12]
 [ 4  4  4 ... 13 12 11]
 [ 3  2  2 ... 13 12 11]
 ...
 [ 6  7  7 ... 15 13 13]
 [ 5  6  7 ... 15 13 13]
 [ 8  8  8 ... 15 13 13]]
./naman/face5.jpg
[[ 8  6  4 ... 30 27 26]
 [ 5  4  4 ... 31 29 28]
 [ 5  6  6 ... 30 29 27]
 ...
 [66 73 91 ... 30 30 30]
 [69 72 88 ... 32 31 30]
 [73 71 85 ... 34 32 30]]
./naman/face6.jpg
[[14 15 17 ... 39 35 33]
 [12 14 15 ... 38 34 32]
 [ 9 11 12 ... 37 34 32]
 ...
 [32 45 64 ... 40 39 37]
 

[[ 47  48  49 ...  53  54  55]
 [ 46  47  48 ...  54  55  55]
 [ 46  46  47 ...  56  56  56]
 ...
 [109 109 109 ...  77  78  78]
 [108 109 109 ...  80  81  81]
 [108 108 109 ...  80  78  77]]
./naman/face53.jpg
[[ 61  61  61 ... 113 113 115]
 [ 62  62  63 ... 113 113 115]
 [ 61  62  63 ... 113 113 115]
 ...
 [118 116 114 ... 192 190 192]
 [121 120 117 ... 193 190 192]
 [123 122 120 ... 193 190 192]]
./naman/face54.jpg
[[ 38  39  41 ... 125 126 126]
 [ 38  38  41 ... 125 126 127]
 [ 38  39  41 ... 124 125 126]
 ...
 [ 54  54  53 ...  78  79  80]
 [ 54  54  53 ...  80  81  82]
 [ 54  54  53 ...  80  82  83]]
./naman/face55.jpg
[[ 50  49  49 ... 127 124 119]
 [ 52  51  50 ... 127 124 118]
 [ 53  52  51 ... 128 125 119]
 ...
 [ 97  96  96 ... 198 197 197]
 [ 99  99  99 ... 178 184 195]
 [101 101 102 ... 133 152 175]]
./naman/face56.jpg
[[ 52  53  52 ...  53  53  51]
 [ 51  52  53 ...  54  53  51]
 [ 51  52  54 ...  54  53  51]
 ...
 [116 123 123 ... 195 191 193]
 [117 126 125 ... 195 188 1

[[132 132 132 ... 135 134 134]
 [133 133 133 ... 134 135 135]
 [133 132 132 ... 134 135 135]
 ...
 [175 176 177 ... 188 188 188]
 [173 173 174 ... 188 188 188]
 [173 172 173 ... 188 188 188]]
./naman/face96.jpg
[[133 132 131 ... 134 133 131]
 [133 132 131 ... 132 132 132]
 [133 132 132 ... 132 133 133]
 ...
 [171 172 173 ... 187 188 188]
 [169 170 171 ... 188 188 189]
 [161 162 164 ... 188 188 189]]
./naman/face97.jpg
[[131 132 132 ... 131 132 133]
 [131 132 132 ... 134 134 135]
 [131 132 132 ... 134 134 134]
 ...
 [166 167 168 ... 189 189 189]
 [162 163 164 ... 190 190 190]
 [159 159 159 ... 190 191 191]]
./naman/face98.jpg
[[125 117 108 ... 131 131 132]
 [124 117 108 ... 131 131 131]
 [122 118 108 ... 132 132 131]
 ...
 [172 174 175 ... 189 189 189]
 [174 177 178 ... 189 189 189]
 [171 175 176 ... 188 188 188]]
./naman/face99.jpg
[[ 71  67  63 ... 128 128 128]
 [ 66  60  56 ... 126 126 126]
 [ 56  51  48 ... 128 129 130]
 ...
 [156 156 155 ... 191 191 191]
 [154 154 155 ... 192 192 1

In [18]:
import cv2
import numpy as np
import webbrowser
import os

face_classifier = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

def face_detector(img, size=0.5):
    
    # Convert image to grayscale
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_classifier.detectMultiScale(gray, 1.3, 5)
    if faces is ():
        return img, []
    
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        roi = img[y:y+h, x:x+w]
        roi = cv2.resize(roi, (200, 200))
    return img, roi


# Open Webcam
cap = cv2.VideoCapture(0)

while True:

    ret, frame = cap.read()
    
    image, face = face_detector(frame)
    
    try:
        face = cv2.cvtColor(face, cv2.COLOR_BGR2GRAY)

        # Pass face to prediction model
        # "results" comprises of a tuple containing the label and the confidence value
        results = vimal_model.predict(face)
        print(results)
        if results[1] < 500:
            confidence = int( 100 * (1 - (results[1])/400) )
            display_string = str(confidence) + '% Confident it is User'
            
        cv2.putText(image, display_string, (100, 120), cv2.FONT_HERSHEY_COMPLEX, 1, (255,120,150), 2)
        
        if confidence > 90:
            cv2.putText(image, "Hey Vimal", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
            cv2.imshow('Face Recognition', image )
                       
        else:
            cv2.putText(image, "Locked", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,0,255), 2)
            cv2.imshow('Face Recognition', image )

    except:
        cv2.putText(image, "No Face Found", (220, 120) , cv2.FONT_HERSHEY_COMPLEX, 1, (0,0,255), 2)
        cv2.putText(image, "Locked", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,0,255), 2)
        cv2.imshow('Face Recognition', image )
        pass
        
    if cv2.waitKey(1) == 13: #13 is the Enter Key
        break
        
cap.release()
cv2.destroyAllWindows()   

(2, 23.28966773073017)
(5, 24.099541160114107)
(10, 22.850868818566976)
(10, 24.21766560745845)
(50, 22.591933683527483)
(50, 21.940761879852232)
(10, 21.917878836548283)
(10, 21.82595855525252)
(21, 22.737577000463205)
(50, 21.694568670506566)
(10, 23.825957813610174)
(8, 22.976347098423812)
(21, 21.39450549730147)
(50, 21.18986888144188)
(10, 21.41124936019708)
(10, 22.23927701604285)
(49, 21.812955822138484)
(13, 22.12048717120863)
(10, 21.388378020742458)
(48, 21.377945312425926)
(33, 20.121486997105922)
(29, 20.141954313165993)
(34, 20.465889870976532)
(7, 22.30826541420956)
(69, 23.84449783011435)
(82, 21.42552056396422)
(75, 26.957325491933293)
(81, 24.094607740537693)
(77, 34.43214779131624)
(75, 32.366653335790886)
(75, 28.371578833073983)
(75, 29.379801256403358)
(75, 31.989314278842937)
(73, 35.17574523524287)
(73, 33.96678119825201)
(73, 32.206136127355684)
(73, 32.06812226669173)
(72, 31.54788433187087)
(54, 31.569329241480055)
(70, 27.15597669307454)
(68, 25.0803083383329